x-common-image: &common-image
  image: ${RADICAL_ORBIT_IMAGE:-radicalcybertools/radical.orbit}:${RADICAL_ORBIT_TAG:-latest}

x-endpoint-service: &endpoint-service
  <<: *common-image
  environment:
    - RADICAL_ORBIT_BRIDGE_URL=https://${RADICAL_ORBIT_BRIDGE_HOSTNAME:-bridge}:8000
  command: [ "bash", "-c", "radical-orbit-endpoint-wrapper.sh -n $$(hostname) --plugins psij,rhapsody,staging,task_dispatcher" ]
  volumes:
    - radical-orbit-volume:/app:ro
  networks:
    - radical-orbit-network
  depends_on:
    image-builder:
      condition: service_completed_successfully
    bridge:
      condition: service_healthy

services:

  image-builder:
    <<: *common-image
    container_name: radical-orbit-image-builder
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        RADICAL_ORBIT_BRANCH: ${RADICAL_ORBIT_BRANCH:-master}
        GENERATE_BRIDGE_CERT: "true"
        BRIDGE_IP: "127.0.0.1"
        BRIDGE_HOSTNAME: ${RADICAL_ORBIT_BRIDGE_HOSTNAME:-bridge}
    command: [ "echo", "Build complete" ]
    networks:
      - radical-orbit-network

  bridge:
    <<: *common-image
    container_name: radical-orbit-bridge
    hostname: ${RADICAL_ORBIT_BRIDGE_HOSTNAME:-bridge}
    command: [ "radical-orbit-bridge.py" ]
    healthcheck:
      test:
        - CMD-SHELL
        - "timeout 1 bash -c '</dev/tcp/localhost/8000'"
      interval: 5s
      timeout: 10s
      retries: 15
      start_period: 30s
    ports:
      - "8000:8000"
    volumes:
      - radical-orbit-volume:/app
    networks:
      - radical-orbit-network
    depends_on:
      image-builder:
        condition: service_completed_successfully

  endpoint-a:
    <<: *endpoint-service
    container_name: radical-orbit-endpoint-a
    hostname: endpoint_a

  endpoint-b:
    <<: *endpoint-service
    container_name: radical-orbit-endpoint-b
    hostname: endpoint_b

  client:
    <<: *common-image
    container_name: radical-orbit-client
    hostname: client
    environment:
      - RADICAL_ORBIT_BRIDGE_URL=https://${RADICAL_ORBIT_BRIDGE_HOSTNAME:-bridge}:8000
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - radical-orbit-volume:/app:ro
    networks:
      - radical-orbit-network
    depends_on:
      image-builder:
        condition: service_completed_successfully
      bridge:
        condition: service_healthy
      endpoint-a:
        condition: service_started
      endpoint-b:
        condition: service_started

volumes:
  radical-orbit-volume:
    name: radical-orbit-volume

networks:
  radical-orbit-network:
    name: radical-orbit-network
