
import logging

log = logging.getLogger(__name__)


# ── Public client surface — bind these BEFORE the plugin imports ─────────────

from .plugin_base           import Plugin  # noqa: F401
from .plugin_session_base   import PluginSession  # noqa: F401
from .ui_schema             import (UIConfig, UIForm, UIField,  # noqa: F401
                                    UIMonitor, UINotifications,
                                    ui_config_to_dict)

from .broker            import Broker  # noqa: F401
from .runtime           import EndpointRuntime  # noqa: F401
from .client            import PluginClient  # noqa: F401

# Public alias — the participant star has one hub (the active broker, still
# reached through the ``Broker`` name until the rename PR) and one node type (the
# endpoint runtime).  ``Endpoint`` is the natural counterpart to ``Broker``.
Endpoint = EndpointRuntime


# ── Plugins ──────────────────────────────────────────────────────────────────

from .plugin_xgfabric      import PluginXGFabric      # noqa: F401
from .plugin_iri_connect   import PluginIRIConnect    # noqa: F401
from .plugin_sfapi_connect import PluginSFAPIConnect  # noqa: F401
from .plugin_queue_info    import PluginQueueInfo     # noqa: F401
from .plugin_sysinfo    import PluginSysInfo  # noqa: F401
from .plugin_staging    import PluginStaging  # noqa: F401
from .plugin_math       import PluginMath     # noqa: F401
from .plugin_task_dispatcher import PluginTaskDispatcher  # noqa: F401
from .plugin_replay      import PluginReplay  # noqa: F401

# Optional plugins with external dependencies.
try:
    from .plugin_lucid import PluginLucid  # noqa: F401
except ImportError as e:
    log.warning('optional plugin "lucid" not loaded: %s', e)

try:
    from .plugin_psij import PluginPSIJ  # noqa: F401
except ImportError as e:
    log.warning('optional plugin "psij" not loaded: %s', e)

try:
    from .plugin_rhapsody import PluginRhapsody  # noqa: F401
except ImportError as e:
    log.warning('optional plugin "rhapsody" not loaded: %s', e)

try:
    from .plugin_globus import PluginGlobus  # noqa: F401
except ImportError as e:
    log.warning('optional plugin "globus" not loaded: %s', e)


# ── Version (generated at install time) ──────────────────────────────────────

# _version.py is generated by setup.py at install time and is
# git-ignored.  When running from an uninstalled source tree the
# import will fail and we fall back to dev markers.
try:
    from ._version import version, version_detail  # noqa: F401
except ImportError:
    version        = 'unknown'
    version_detail = 'unknown'

__version__ = version

