#!/usr/bin/env python3

__author__    = 'Radical Development Team'
# pylint: disable=protected-access,unused-import,unused-variable,not-callable,unused-argument
__email__     = 'radical@radical-project.org'
__copyright__ = 'Copyright 2024, RADICAL@Rutgers'
__license__   = 'MIT'


"""
Test for version information.
"""

import importlib.util

import pytest

import radical.orbit as re


# ``_version.py`` is generated by setup.py at build/install time; running
# straight from the source tree (PYTHONPATH=src, no build) leaves it
# absent and radical.orbit.version falls back to 'unknown'.  Skip the
# format check in that case — it is only meaningful against a build.
_HAS_BUILT_VERSION = importlib.util.find_spec('radical.orbit._version') \
    is not None


def test_version_exists():
    """Test that version attribute exists."""
    assert hasattr(re, 'version')
    assert hasattr(re, '__version__')


def test_version_is_string():
    """Test that version is a string."""
    assert isinstance(re.version, str)
    assert isinstance(re.__version__, str)


def test_version_not_empty():
    """Test that version is not empty."""
    assert re.version
    assert re.__version__
    assert re.version != ''
    assert re.__version__ != ''


def test_version_matches():
    """Test that version and __version__ match."""
    assert re.version == re.__version__


@pytest.mark.skipif(not _HAS_BUILT_VERSION,
                    reason="_version.py absent (running from un-built "
                           "source tree); version format only meaningful "
                           "against a build")
def test_version_format():
    """Test that version has expected format (not 'unknown')."""
    # Should be either a version number or git hash, not 'unknown'
    assert re.version != 'unknown'
    assert len(re.version) > 0



