x-common-image: &common-image
  image: ${RADICAL_EDGE_IMAGE:-radicalcybertools/radical.edge}:${RADICAL_EDGE_TAG:-latest}

x-edge-service: &edge-service
  <<: *common-image
  environment:
    - RADICAL_BRIDGE_URL=https://${RADICAL_BRIDGE_HOSTNAME:-bridge}:8000
  command: [ "bash", "-c", "radical-edge-wrapper.sh -n $$(hostname) --plugins psij,rhapsody,staging,task_dispatcher" ]
  volumes:
    - radical-edge-volume:/app:ro
  networks:
    - radical-edge-network
  depends_on:
    image-builder:
      condition: service_completed_successfully
    bridge:
      condition: service_healthy

services:

  image-builder:
    <<: *common-image
    container_name: radical-edge-image-builder
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        RADICAL_EDGE_BRANCH: ${RADICAL_EDGE_BRANCH:-master}
        GENERATE_BRIDGE_CERT: "true"
        BRIDGE_IP: "127.0.0.1"
        BRIDGE_HOSTNAME: ${RADICAL_BRIDGE_HOSTNAME:-bridge}
    command: [ "echo", "Build complete" ]
    networks:
      - radical-edge-network

  bridge:
    <<: *common-image
    container_name: radical-bridge
    hostname: ${RADICAL_BRIDGE_HOSTNAME:-bridge}
    command: [ "radical-edge-bridge.py" ]
    healthcheck:
      test:
        - CMD-SHELL
        - "timeout 1 bash -c '</dev/tcp/localhost/8000'"
      interval: 5s
      timeout: 10s
      retries: 15
      start_period: 30s
    ports:
      - "8000:8000"
    volumes:
      - radical-edge-volume:/app
    networks:
      - radical-edge-network
    depends_on:
      image-builder:
        condition: service_completed_successfully

  edge-a:
    <<: *edge-service
    container_name: radical-edge-a
    hostname: edge_a

  edge-b:
    <<: *edge-service
    container_name: radical-edge-b
    hostname: edge_b

  client:
    <<: *common-image
    container_name: radical-edge-client
    hostname: client
    environment:
      - RADICAL_BRIDGE_URL=https://${RADICAL_BRIDGE_HOSTNAME:-bridge}:8000
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - radical-edge-volume:/app:ro
    networks:
      - radical-edge-network
    depends_on:
      image-builder:
        condition: service_completed_successfully
      bridge:
        condition: service_healthy
      edge-a:
        condition: service_started
      edge-b:
        condition: service_started

volumes:
  radical-edge-volume:
    name: radical-edge-volume

networks:
  radical-edge-network:
    name: radical-edge-network
